# permissions for end users to edit sandboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sandbox-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sandbox
    app.kubernetes.io/part-of: sandbox
    app.kubernetes.io/managed-by: kustomize
  name: sandbox-editor-role
rules:
- apiGroups:
  - stakator.io.stakator.io
  resources:
  - sandboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stakator.io.stakator.io
  resources:
  - sandboxes/status
  verbs:
  - get
